kind: pipeline
name: python-docs

steps:
- name: publish
  image: plugins/docker:latest
  settings:
    auto_tag: true
    username:
      from_secret: u
    password:
      from_secret: p
    repo: buglan/python-docs

- name: deploy
  image: appleboy/drone-ssh
  pull: true
  settings:
    host: buglan.org
    port: 28379
    user: root
    key:
      from_secret: k
    script:
    - docker pull buglan/python-docs:latest
    - docker rm -f python-docs
    - docker run --name=python-docs -p 4001:4001 -d buglan/python-docs

- name: notify
  image: plugins/gitter
  settings:
    webhook: https://webhooks.gitter.im/e/bf9402f8c689cffaf87c